CREATE TABLE Member (
	UserID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nickname VARCHAR(32) NOT NULL,
	Username VARCHAR(32) NOT NULL,
	UserType INT NOT NULL,
	Password VARCHAR(32) NOT NULL
);

CREATE TABLE Course(
	CourseID  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY,
	Name      VARCHAR(32) NOT NULL,
	Cap       INT NOT NULL,
	TeacherID VARCHAR(32)
};

CREATE TABLE SCourse (
	CourseID BIGINT UNSIGNED NOT NULL,
	UserID   BIGINT UNSIGNED NOT NULL,
}

INSERT INTO Menber VALUES()